location ~ ^/skins/(?<skin_asset>[^/]+\.png)$ {
    alias /www/wwwroot/starmc-api/public/skins/$skin_asset;
    expires 30d;
    add_header Cache-Control "public, immutable";
    access_log off;
    sendfile on;
    sendfile_max_chunk 1m;
    tcp_nopush on;
    open_file_cache max=2000 inactive=20s;
    open_file_cache_valid 60s;
    open_file_cache_min_uses 2;
    open_file_cache_errors off;
}
